export default {
  '.xls': 'atom-excel',
  '.xlsx': 'atom-excel',
  '.doc': 'atom-word',
  '.docx': 'atom-word',
  '.ppt': 'atom-ppt',
  '.pptx': 'atom-ppt',
  '.pdf': 'atom-pdf',
  '.txt': 'atom-txt',
  '.wps': 'atom-wps',
  '.png': 'atom-image',
  '.jpg': 'atom-image',
  '.jpeg': 'atom-image',
  '.bmp': 'atom-image',
  '.gif': 'atom-image',
  '.svg': 'atom-image',
  '.ico': 'atom-image',
  '.mp4': 'atom-video',
  '.rmvb': 'atom-video',
  '.avi': 'atom-video',
  '.mkv': 'atom-video',
  '.wmv': 'atom-video',
  '.mpeg': 'atom-radio',
  '.mp3': 'atom-radio',
  '.wav': 'atom-radio',
  default: 'atom-file',
}
